name: Semgrep

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  semgrep:
    permissions:
      contents: read 
      security-events: write 
      actions: read
    name: Scan
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3
      - uses: returntocorp/semgrep-action@fcd5ab7459e8d91cb1777481980d1b18b4fc6735
        with:
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          publishDeployment: ${{ secrets.SEMGREP_DEPLOYMENT_ID }}
          generateSarif: "1"

      
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
        if: always()
