name: Semgrep

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  semgrep:
    name: Scanner
    runs-on: ubuntu-latest
    container: 
      image: returntocorp/semgrep
    steps:
      
      - uses: actions/checkout@v3
      - run:  semgrep ci --config=auto --sarif --output=semgrep.sarif || true
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
        if: always()
